pipeline{
    agent any
    stages {
        stage("Build"){
            steps {
                dir("hdfctest"){
                    sh "mvn -B -DskipTests clean package"
                }
            }
        }
        stage("Test"){
            steps{
                dir("hdfctest"){
                    sh "mvn test"
                }
            }
        }
        stage("Deliver"){
            steps{
                sh "./jenkins/scripts/deliver.sh"
            }
        }
    }
}
